
"use client";

import React from 'react';
import { Navbar } from '@/components/Navbar';
import { Footer } from '@/components/Footer';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from "@/components/ui/card";
import { 
  ArrowLeft, 
  ShoppingBag, 
  Loader2, 
  Phone, 
  MapPin, 
  Calendar, 
  User, 
  Trash2, 
  CheckCircle, 
  XCircle, 
  Download, 
  Printer,
  FileText
} from 'lucide-react';
import Link from 'next/link';
import { useFirestore, useCollection, useMemoFirebase } from '@/firebase';
import { collection, query, orderBy, doc } from 'firebase/firestore';
import { updateDocumentNonBlocking, deleteDocumentNonBlocking } from '@/firebase/non-blocking-updates';
import { Badge } from '@/components/ui/badge';
import { jsPDF } from "jspdf";
import autoTable from 'jspdf-autotable';

export default function AdminOrders() {
  const db = useFirestore();
  const ordersRef = useMemoFirebase(() => query(collection(db, 'orders'), orderBy('createdAt', 'desc')), [db]);
  const { data: orders, isLoading } = useCollection(ordersRef);

  const handleUpdateStatus = (id: string, newStatus: string) => {
    updateDocumentNonBlocking(doc(db, 'orders', id), { status: newStatus });
  };

  const handleDeleteOrder = (id: string) => {
    if (confirm("ARE YOU SURE YOU WANT TO PERMANENTLY DELETE THIS ORDER RECORD?")) {
      deleteDocumentNonBlocking(doc(db, 'orders', id));
    }
  };

  const generateInvoice = (order: any) => {
    const doc = new jsPDF();
    
    // Header
    doc.setFillColor(255, 140, 0); // Orange
    doc.rect(0, 0, 210, 40, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont("helvetica", "bold");
    doc.text("SS SMART HAAT", 15, 25);
    doc.setFontSize(10);
    doc.text("PREMIUM MARKETPLACE INVOICE", 15, 32);

    // Order Info
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("INVOICE TO:", 15, 55);
    doc.setFont("helvetica", "normal");
    doc.text(`Customer Name: ${order.customerName}`, 15, 62);
    doc.text(`Phone: ${order.customerPhone}`, 15, 68);
    doc.text(`Address: ${order.customerAddress}`, 15, 74);

    doc.setFont("helvetica", "bold");
    doc.text("ORDER DETAILS:", 130, 55);
    doc.setFont("helvetica", "normal");
    doc.text(`Order ID: #${order.id.slice(0, 8).toUpperCase()}`, 130, 62);
    doc.text(`Date: ${new Date(order.createdAt).toLocaleDateString()}`, 130, 68);
    doc.text(`Status: ${order.status}`, 130, 74);

    // Table
    autoTable(doc, {
      startY: 90,
      head: [['PRODUCT NAME', 'UNIT PRICE', 'QUANTITY', 'TOTAL']],
      body: [
        [order.productName, `BDT ${order.productPrice.toLocaleString()}`, '1', `BDT ${order.productPrice.toLocaleString()}`]
      ],
      headStyles: { fillColor: [255, 140, 0], textColor: [255, 255, 255] },
      styles: { fontSize: 10, cellPadding: 5 }
    });

    // Total
    const finalY = (doc as any).lastAutoTable.finalY + 10;
    doc.setFont("helvetica", "bold");
    doc.text(`GRAND TOTAL: BDT ${order.productPrice.toLocaleString()}`, 130, finalY + 10);

    // Footer
    doc.setFontSize(8);
    doc.setFont("helvetica", "italic");
    doc.text("Thank you for choosing SS SMART HAAT. For any queries, contact our support.", 15, 280);
    doc.text("Generated by SS SMART HAAT System", 140, 280);

    doc.save(`Invoice_${order.customerName}_${order.id.slice(0, 5)}.pdf`);
  };

  return (
    <div className="min-h-screen flex flex-col bg-background">
      <Navbar />
      
      <main className="flex-grow container mx-auto px-4 py-12">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-12">
          <div className="flex items-center gap-4">
            <Button asChild variant="ghost" className="rounded-none hover:bg-white/5 text-white p-2 h-12 w-12">
              <Link href="/admin"><ArrowLeft className="h-6 w-6" /></Link>
            </Button>
            <div className="space-y-1">
              <p className="text-[10px] font-black text-orange-600 uppercase tracking-widest">Executive Management</p>
              <h1 className="text-4xl font-black uppercase tracking-tighter text-white">ORDER INTELLIGENCE</h1>
            </div>
          </div>
          <div className="flex items-center gap-3">
             <Badge className="bg-white/5 border-white/10 text-white font-black text-[12px] uppercase rounded-none px-6 py-3 h-14">
              {orders?.length || 0} TOTAL REPORTS
            </Badge>
          </div>
        </div>

        {isLoading ? (
          <div className="flex flex-col items-center justify-center py-40 gap-4">
            <Loader2 className="h-12 w-12 text-orange-600 animate-spin" />
            <p className="text-[10px] font-black uppercase text-orange-600 animate-pulse tracking-[0.3em]">Synchronizing Order Data...</p>
          </div>
        ) : !orders || orders.length === 0 ? (
          <div className="text-center py-32 border border-dashed border-white/10 bg-white/[0.02]">
            <ShoppingBag className="h-16 w-16 text-white/5 mx-auto mb-6" />
            <p className="text-sm font-black uppercase text-muted-foreground tracking-[0.5em]">No records found in the system archive.</p>
          </div>
        ) : (
          <div className="space-y-6">
            {orders.map((order) => (
              <Card key={order.id} className="bg-card border-white/5 rounded-none overflow-hidden hover:border-orange-600/30 transition-all shadow-2xl group">
                <div className="flex flex-col xl:flex-row">
                  {/* ORDER STATUS & BASIC INFO */}
                  <div className="p-8 xl:w-1/4 bg-white/[0.02] border-b xl:border-b-0 xl:border-r border-white/5 flex flex-col justify-between">
                    <div className="space-y-4">
                      <div className="flex items-center justify-between">
                        <Badge className={`rounded-none text-[9px] font-black uppercase px-3 py-1.5 ${
                          order.status === 'PENDING' ? 'bg-yellow-500/20 text-yellow-500 border-yellow-500/30' : 
                          order.status === 'CONFIRMED' ? 'bg-blue-500/20 text-blue-500 border-blue-500/30' :
                          order.status === 'CANCELLED' ? 'bg-red-500/20 text-red-500 border-red-500/30' :
                          'bg-green-500/20 text-green-500 border-green-500/30'
                        } border`}>
                          {order.status}
                        </Badge>
                        <span className="text-[9px] font-mono text-muted-foreground uppercase flex items-center gap-2">
                          <Calendar className="h-3 w-3" /> {new Date(order.createdAt).toLocaleDateString()}
                        </span>
                      </div>
                      <div className="space-y-1">
                        <p className="text-[9px] font-black text-orange-600 uppercase tracking-widest">ORDER ID</p>
                        <p className="text-xs font-mono text-white opacity-40">#{order.id.toUpperCase()}</p>
                      </div>
                      <div className="space-y-1">
                        <p className="text-[9px] font-black text-orange-600 uppercase tracking-widest">PRODUCT</p>
                        <h3 className="text-xl font-black text-white uppercase tracking-tighter leading-tight">{order.productName}</h3>
                        <p className="text-2xl font-black text-white tracking-tighter">৳{order.productPrice.toLocaleString()}</p>
                      </div>
                    </div>
                  </div>

                  {/* CUSTOMER DETAILS */}
                  <div className="p-8 xl:w-2/4 grid grid-cols-1 md:grid-cols-2 gap-8 items-center bg-black/40">
                    <div className="space-y-6">
                      <div className="flex items-start gap-4">
                        <div className="h-10 w-10 bg-orange-600/10 flex items-center justify-center shrink-0 border border-orange-600/20">
                          <User className="h-5 w-5 text-orange-600" />
                        </div>
                        <div>
                          <p className="text-[9px] font-black text-muted-foreground uppercase tracking-widest">Customer Name</p>
                          <p className="text-[14px] font-black text-white uppercase">{order.customerName}</p>
                        </div>
                      </div>
                      <div className="flex items-start gap-4">
                        <div className="h-10 w-10 bg-orange-600/10 flex items-center justify-center shrink-0 border border-orange-600/20">
                          <Phone className="h-5 w-5 text-orange-600" />
                        </div>
                        <div>
                          <p className="text-[9px] font-black text-muted-foreground uppercase tracking-widest">Direct Contact</p>
                          <p className="text-[14px] font-black text-white uppercase font-mono">{order.customerPhone}</p>
                        </div>
                      </div>
                    </div>
                    <div className="flex items-start gap-4 h-full md:border-l md:border-white/5 md:pl-8">
                      <div className="h-10 w-10 bg-orange-600/10 flex items-center justify-center shrink-0 border border-orange-600/20">
                        <MapPin className="h-5 w-5 text-orange-600" />
                      </div>
                      <div>
                        <p className="text-[9px] font-black text-muted-foreground uppercase tracking-widest">Delivery Address</p>
                        <p className="text-[13px] font-black text-white uppercase leading-relaxed max-w-xs">{order.customerAddress}</p>
                      </div>
                    </div>
                  </div>

                  {/* ACTIONS */}
                  <div className="p-8 xl:w-1/4 flex flex-col justify-center gap-3 bg-white/[0.01]">
                    <div className="grid grid-cols-2 gap-2">
                      <Button 
                        onClick={() => handleUpdateStatus(order.id, 'CONFIRMED')}
                        className="bg-blue-600 hover:bg-blue-700 text-white font-black text-[10px] uppercase rounded-none h-12 shadow-lg shadow-blue-600/10"
                      >
                        <CheckCircle className="mr-2 h-4 w-4" /> CONFIRM
                      </Button>
                      <Button 
                        onClick={() => handleUpdateStatus(order.id, 'CANCELLED')}
                        variant="outline"
                        className="border-red-600/50 text-red-500 hover:bg-red-600 hover:text-white font-black text-[10px] uppercase rounded-none h-12"
                      >
                        <XCircle className="mr-2 h-4 w-4" /> CANCEL
                      </Button>
                    </div>
                    
                    <Button 
                      onClick={() => handleUpdateStatus(order.id, 'DELIVERED')}
                      className="bg-green-600 hover:bg-green-700 text-white font-black text-[10px] uppercase rounded-none h-12 shadow-lg shadow-green-600/10"
                    >
                      <ShoppingBag className="mr-2 h-4 w-4" /> MARK DELIVERED
                    </Button>

                    <div className="grid grid-cols-2 gap-2 mt-2">
                      <Button 
                        variant="secondary"
                        onClick={() => generateInvoice(order)}
                        className="bg-white/5 hover:bg-white/10 text-white font-black text-[10px] uppercase rounded-none h-12 border border-white/10"
                      >
                        <Download className="mr-2 h-4 w-4 text-orange-600" /> PDF INVOICE
                      </Button>
                      <Button 
                        variant="ghost"
                        onClick={() => handleDeleteOrder(order.id)}
                        className="text-muted-foreground hover:text-red-500 hover:bg-red-500/10 rounded-none h-12 uppercase text-[10px] font-black"
                      >
                        <Trash2 className="mr-2 h-4 w-4" /> REMOVE
                      </Button>
                    </div>
                  </div>
                </div>
              </Card>
            ))}
          </div>
        )}
      </main>
      
      <Footer />
    </div>
  );
}
